= Libraries and Toolkits

There are many alternative libraries and toolkits. These are implemented in a variety of programming languages, offering programmers native interfaces in their preferred language.

The following sections list some of the best libraries and toolkits, organized by programming languages.
Part of https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch03.asciidoc#alternative-clients-libraries-and-toolkits


== JavaScript
http://bcoin.io/[bcoin]:: A modular and scalable full-node implementation with API
* BTC: https://github.com/bcoin-org/bcoin
* BCC: https://github.com/bcoin-org/bcash
https://bitcore.io/[Bitcore] :: Full node, API, and library by Bitpay
* BTC: https://github.com/bitpay
* BTX: https://github.com/LIMXTEC
https://github.com/bitcoinjs[Tools]:: Open Source Organisation for Bitcoin JavaScript libraries
* BTC: https://github.com/bitcoinjs/bitcoinjs-lib
* LTC: https://github.com/RossMathew/litecoinjs

== Java
https://bitcoinj.github.io[bitcoinj]:: A Java full-node client library
* BTC: https://github.com/bitcoinj/bitcoinj
* BTX: https://github.com/LIMXTEC/bitcorej
* BCC: https://github.com/GENERALBYTESCOM/bitcoincashj
* LTC: https://github.com/czarcoin-evolve/litecoinj
* Speedcoin: https://github.com/spdcoin/Speedcoinj
* PAY Coin: https://github.com/projectpai/bitcoinj/tree/paicoin


== PHP
https://github.com/bit-wasp/bitcoin-php[bitwasp/bitcoin]:: A PHP bitcoin library, and related projects
https://github.com/cryptoapi/Payment-Gateway[PHP Payment Class]:: Bitcoin/Altcoins PHP Payment Class.
* https://github.com/cryptoapi/
* https://gourl.io/coin-voting.html
* https://gourl.io/development.html

== Python
https://github.com/richardkiss/pycoin[pycoin]:: A Python bitcoin library by Richard Kiss


== Rust
https://github.com/apoelstra/rust-bitcoin[rust-bitcoin]:: Rust bitcoin library for serialization, parsing, and API calls


== C#
https://github.com/MetacoSA/NBitcoin[NBitcoin]:: Comprehensive bitcoin library for the .NET framework


Many more libraries exist in a variety of other programming languages and more are created all the time.
